ANON_NAME_MAX_LENGTH = 50
EMAIL_MAX_LENGTH = 255

BOARD_NAME_MAX_LENGTH = 30
BOARD_CATEGORY_NAME_MAX_LENGTH = 30
THREAD_NAME_MAX_LENGTH = 100
BODY_MAX_LENGTH = 1000

class Config:
    SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:Si1573555%40si@localhost:3306/ochan"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = "bazinga"